[[cells]]
name = "joyid-lib-demo"
enable_type_id = true
location = { file = "${WORK_DIR}/build/release/joyid-lib-demo" }

 [[cells]]
 name = "joyid-lib"
 enable_type_id = true
 location = { file = "${WORK_DIR}/ckb-lib-joyid/build/joyid.so" }

# reference to on-chain cells
 [[cells]]
 name = "secp256k1_data"
 enable_type_id = false
 # testnet
 location = { tx_hash = "0x8f8c79eb6671709633fe6a46de93c0fedc9c1b8a6527a18d3983879542635c9f", index = 3 }
 

# Dep group cells
[[dep_groups]]
name = "dep_group"
cells = [
  "joyid-lib-demo",
  "joyid-lib",
  "secp256k1_data",
]

# # Replace with your own lock if you want to unlock deployed cells.
# # For example the secp256k1 lock
# [lock]
# code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
# args = "0x0000000000000000000000000000000000000000"
# hash_type = "type"

